 pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Building foodie--cape...'
            }
        }
        stage('Test') {
            steps {
                echo 'Running tests...'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying foodie--cape...'
            }
        }
    }
}
