apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-new
  template:
    metadata:
      labels:
        app: backend-new
    spec:
      containers:
      - name: backend
        image: praveen7446/foodiecape-backend:v2
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: mongodb://mongodb-service:27017/foodie
---
apiVersion: v1
kind: Service
metadata:
  name: backend-new-service
spec:
  selector:
    app: backend-new
  ports:
  - port: 5000
    targetPort: 5000
  type: NodePort